#!/mnt/b/java/mc/src/alias/rb.sh

BaseName = File.basename(__FILE__)
Directory = File.expand_path __dir__

PPID = Process.ppid
Parent = File.basename(`ps -p #{PPID} -o comm=`.strip).strip

gcc_name_split = BaseName.split('-')
gcc_pre_name = gcc_name_split[0...-1].join('-')
gcc_post_name = gcc_name_split[-1]
gcc_name = gcc_pre_name.empty? ? "gcc-#{gcc_post_name}" : "#{gcc_pre_name}-gcc-#{gcc_post_name}"

puts gcc_name

SearchName = (Parent.start_with?('gcc-') || Parent.include?('-gcc-')) ? BaseName : gcc_name

adjusted_paths=[]
executable = nil

#if File.executable?(File.join(Directory, ".#{BaseName}"))
#  executable = File.join(Directory, ".#{BaseName}")
#end

if executable.nil?
	for p in ENV['PATH'].split(':')
		next unless File.directory?(p)
		next if (File.realdirpath(Directory) == File.realdirpath(p))
		if executable.nil?
			path = File.join(p, SearchName)
			if File.executable?(path)
				executable = path
			end
		end
		adjusted_paths << p
	end
end

if executable.nil?
	STDERR.puts "#{BaseName}: command not found"
	exit 1
end

ENV['PATH'] = adjusted_paths.join(':')

exec(executable, *ARGV)

STDERR.puts "#{BaseName}: severe execution error"
exit 2
